INSERT INTO `pokedex` (`name`, `type1`, `type2`, `description`, `height`, `weight`, `evolution_name`, `if_evolution`, `hp`, `att`, `def`, `att_spe`, `def_spe`, `speed`, `species`) VALUES
('Bulbasaur', 'Grass', '· Poison', 'A strange seed was planted on its back at birth. The plant sprouts and grows with this pokemon.', 0.7, 6.9, 'Ivysaur #002', 'level 16', 45, 49, 49, 65, 65, 45, 'Seed Pokemon'),
('Ivysaur', 'Grass', '· Poison',, 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 1.0, 13.0, 'Venusaur #003','level 32', 60, 62, 63, 80, 80, 60, 'Seed Pokemon'),
('Venusaur', 'Grass', ' · Poison',, 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', 2.0, 100.0, 'Final evolution', 'No requirement', 80, 82, 83, 100, 100, 80, 'Seed Pokemon'),
('Charmander', 'Fire', '', 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.', 0.6, 8.5, 'Charmeleon #005', 'level 16', 39, 52, 43, 60, 50,65, 'Lizard Pokemon'),
('Charmeleon', 'Fire', '', 'When it swings its burning tail, it elevates the temperature to unbearably high levels.', 1.1, 19.0, 'Charizard #006', 36, 58, 64, 80, 65, 58, 80, 'Flame Pokemon'),
('Charizard', 'Fire', '', 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.', 1.7, 90.5, 'Final evolution', 'No requirement', 78, 84, 78, 109, 85, 100, 'Flame Pokemon'),
('Squirtle','Water', '', 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.', 0.5, 9.0, 'Wartortle #008', 'level 16', 44, 48, 65, 50, 64, 43, 'Tiny Turtle Pokemon'),
('Wartortle', 'Water', '', 'Often hides in water to stalk unwary pray. For swimming fast, it moves its ears to maintain balance.', 1.0, 22.5, 'Blastoise #009', 'level 36', 59, 63, 80, 65, 80, 58, 'Turtle Pokemon'),
('Blastoise', 'Water', '', 'A brutal pokemon with pressurized water jets on its shell. They are used for high speed tackles.', 1.6, 85.5, 'Final evolution', 'No requirement', 79, 83, 100, 85, 105, 78, 'Shellfish Pokemon'),
('Caterpie', 'Bug', '', 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.', 0.3, 2.9, 'Metapod #011', 'level 7', 45, 30, 35, 20, 20, 45, 'Worm Pokemon'),
('Metapod', 'Bug', '', 'This pokemon is vulnerable to attack while its shell is soft, exposing its weak and tender body.', 0.7, 9.9, 'Butterfree #012', 'level 10', 50, 20, 55, 25, 25, 30, 'Cocoon Pokemon'),
('Butterfree', 'Bug', '· Flying', 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.', 1.1, 32.0, 'No evolution', 'No requirement', 60, 45, 50, 90, 80, 70, 'Butterfly Pokemon'),
('Weedle', 'Bug', '· Poison', 'Often found in forest, eating leaves. It has a sharp venomous stinger on its head.', 0.3, 3.2, 'Kakuna #014', 'level 7', 40, 35, 30, 20, 20, 50, 'Hairy Bug Pokemon'),
('Kakuna', 'Bug', '· Poison', 'Almost incapable of moving this pokemon can only harden its shell to protect itself from predators.', 0.6, 10.0, 'Beedrill #015', 'level 10', 45, 25, 50, 25, 25, 35, 'Cocoon Pokemon'),
('Beedrill', 'Bug', '· Poison', 'Flies at high speed and attack using its large venomous stingers on its forelegs and tail.', 1.0, 29.5, 'Final evolution', 'No requirement', 65, 90, 40, 45, 80, 75, 'Poison Bee Pokemon'),
('Pidgey', 'Normal', '· Flying', 'A common sight in forest and ground level to kick up blinding sand.', 0.3, 1.8, 'Pidgeotto #017', 'level 18', 40, 45, 40, 35, 35, 56, 'Tiny Bird Pokemon'),
('Pidgeotto', 'Normal', '· Flying', 'Very protective of its sprawling territorial area, this pokemon will fiercely peck at any intruder.', 1.1, 30.0, 'Pidgeot #018', 'level 36', 63, 60, 55, 50, 50, 71, 'Bird Pokemon'),
('Pidgeot', 'Normal', '· Flying', 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.', 1.5, 39.5, 'Final evolution', 'No requirement', 83, 80, 75, 70, 70, 101, 'Bird Pokemon'),
('Rattata', 'Normal', '', 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.', 0.3, 3.5, 'Raticate #020', 'level 20', 30, 56, 35, 25, 35, 72, 'Mouse Pokemon'),
('Raticate', 'Normal', '', 'It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.', 0.7, 18.5, 'Final evolution', 'No requirement', 55, 81, 60, 50, 70, 97, 'Mouse Pokemon'),
('Spearow', 'Normal', '· Flying', 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.', 0.3, 2.0, 'Fearow #022', 'level 20', 40, 60, 30, 31, 31, 70, 'Tiny Bird Pokemon'),
('Fearow', 'Normal', '· Flying', 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.', 1.2, 38.0, 'Final evolution', 'No requirement', 65, 90, 65, 61, 61, 100, 'Beak Pokemon'),
('Ekans', 'Poison', '', 'Moves silently and stealthily. Eats the eggs of birds, such as Pidgey ans Spearow, whole.', 2.0, 6.9, 'Arbok #024', 'level 22', 35, 60, 44, 40, 54, 55, 'Snake Pokemon'),
('Arbok', 'Poison', '', 'It is rumored that the ferocious warning marking on its belly differ from to area.', 3.5, 65.0, 'Final evolution', 'No requirement', 60, 95, 69, 65, 79, 80, 'Cobra Pokemon'),
('Pikachu', 'Electric', '', 'When several of these pokemon gather, their electricity could build and cause lightning storms.', 0.4, 6.0, 'Raichu #026', 'Thunder stone', 35, 55, 40, 50, 50, 90, 'Mouse Pokemon'),
('Raichu', 'Electric', '', 'Its long tail serves as a ground to protect itself from its own high voltage power.', 0.8, 30.0, 'Final evolution', 'No requirement', 60, 90, 55, 90, 80, 110, 'Mouse Pokemon'),
('Sandshrew', 'Ground', '', 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.', 0.6, 12.0, 'Sandslash #028', 'level 22', 50, 75, 85, 20, 30, 40, 'Mouse Pokemon'),
('Sandslash', 'Ground', '', 'Curls up into a spiny ball when threatened. It can rool while curled up to attack or escape.', 1.0, 29.5, 'Final evolution', 'No requirement', 75, 100, 110, 45, 55, 65, 'Mouse Pokemon'),
('Nidoran♀', 'Poison', '', 'Although small, its venomousbarbs render this pokemon dangerous. The female has smaller horns.', 0.4, 7.0, 'Nidorina #030', 'level 16', 55, 47, 52, 40, 40, 41, 'Poison Pin Pokemon'),
('Nidorina', 'Poison', '', 'The femalehorn develops slowly. Prefers physical attacks such as clawing and biting.', 0.8, 20.0, 'Nidoqueen #031', 'Moon stone', 70, 62, 67, 55, 55, 56, 'Poison Pin Pokemon'),
('Nidoqueen', 'Poison', 'Ground', 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.', 1.3, 60.0, 'Final evolution', 'No requirement', 90, 92, 87, 75, 85, 76, 'Drill Pokemon'),
('Nidoran♂', 'Poison', '', 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.', 0.5, 9.0, 'Nidorino #033', 'level 16', 46, 57, 40, 40, 40, 50, 'Poison Pin Pokemon'),
('Nidorino', 'Poison', '', 'An aggressive pokemon that is quick to attack. The horn on its head secretes a powerful venom.', 0.9, 19.5, 'Nidoking #034', 'Moon stone', 61, 72, 57, 55, 55, 65, 'Poison Pin pokemon'),
('Nidoking', 'Poison', '', 'It uses its powerful tail in battle to smash, constrict, then break the prey s bones.', 1.4, 62.0, 'Final evolution', 'No requirement', 81, 102, 77, 85, 75, 85, 'Drill Pokemon'),
('Clefairy', 'Normal', '', 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.', 0.6, 7.5, 'Clefable #036', 'Moon stone', 70, 45, 48, 60, 65, 35, 'Fairy Pokemon'),
('Clefable', 'Normal', '', 'A timid fairy pokemon that is rarely seen. It will run and hide the moment it senses poeple.', 1.3, 40.0, 'Final evolution', 'No requirement', 95, 70, 73, 95, 90, 60, 'Fairy Pokemon'),
('Vulpix', 'Fire', '', 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older', 0.6, 9.9, 'Nintales #384', 'Fire stone', 38, 41, 40, 50, 65, 65, 'Fox Pokemon'),
('Ninetales', 'Fire', '', 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-years curse.', 1.1, 19.9, 'Final evolution', 'No requirement', 73, 76, 75, 81, 100, 100, 'Fox Pokemon'),
('Jigglypuff', 'Normal', '', 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.', 0.5, 5.5, 'Wigglytuff #040', 'Moon stone', 115, 45, 20, 45, 25, 20, 'Baloon Pokemon'),
('Wigglytuff', 'Normal', '', 'The body is soft and rubberry. hen angered, it will suck in air and inflate itself to an enormous size.', 1.0, 12.0, 'Final evolution', 'No requirement', 140, 70, 45, 85, 50, 45, 'Baloon Pokemon'),
('Zubat', 'Poison', '· Flying', 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach target.', 0.8, 7.5, 'Golbat #042', 'level 22', 40, 45, 35, 30, 40, 55, 'Bat Pokemon'),
('Golbat', 'Poison', '· Flying', 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly', 1.6, 55.0, 'Final evolution', 'No requirement', 75, 80, 70, 65, 75, 90, 'Bat Pokemon'),
('Oddish', 'Grass', '· Poison', 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.', 0.5, 5.4, 'Gloom #044', 'level 21', 45, 50, 55, 75, 65, 30, 'Weed Pokemon'),
('Gloom', 'Grass', '· Poison', 'The fluid that oozes from its mouth is not drool. It is a nectar that is used to attract prey', 0.8, 8.6, 'Vileplume #0045', 'Leaf Stone', 60, 65, 70, 85, 75, 40, 'Weed Pokemon'),
('Vileplume', 'Grass', '· Poison', 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.', 1.2, 18.6, 'Final evolution', 'No requirement', 75, 80, 85, 110, 90, 50, 'Flower Pokemon'),
('Paras', 'Bug', '· Grass', 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.', 0.3, 5.4, 'Parasect #047', 'level 24', 35, 70, 55, 45, 55, 25, 'Mushroom Pokemon'),
('Parasect', 'Bug', '· Grass', 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.', 1.0, 29.5, 'Final evolution', 'No requirement', 60, 95, 80, 60, 80, 30, 'Mushroom Pokemon'),
('Venonat', 'Bug', '· Poison', 'Lives in the shadows of tall trees where it eats insects. it is attracted by light at night', 1.0, 30.0, 'Venomoth #049', 'level 31', 60, 55, 50, 40, 55, 45, 'Insect Pokemon'),
('Venomoth', 'Bug', '· Poison', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
('', '', '', '', , , , , , , , , , , ''),
1normal
2fire
3water
4grass
5electric
6fighting
7poison
8ice
9psychic
10bug
11ghost
12rock
13ground
14flying
15dragon